### ISSUE TITLE
invalid module path error when using gocov-html with gomod enabled project

### ISSUE THREAD

**Issue by chaudharisuresh997** [matm/gocov-html#14]
go version 1.12.5 amd 64
my project is GOMOD enabled
export GO11MODULE=on
go get -v gopkg.in/matm/v1/gocov-html
gives me invalid module path "gopkg.in/matm/v1/gocov-html"

**Comment by matm** [comment]
Hum, there is no reference to `gopkg.in` in the code.
Did you try the instructions in the README?
```
$ go get -u github.com/matm/gocov-html
```
