### ISSUE TITLE
Latest version 1.1.1 breaks go install

### ISSUE THREAD

**Issue by msdean** [matm/gocov-html#20]
Latest version tag seems to be broken:

$ go install github.com/matm/gocov-html@latest
go: github.com/matm/gocov-html@latest: module github.com/matm/gocov-html@latest found (v1.1.1), but does not contain package github.com/matm/gocov-html

I'm using go 1.18.1 on ubuntu18

**Comment by SandroPreuss1234** [comment]
@msdean , we were also affected :wink: 
But after looking into the last changes I found, that also the [README.md](https://github.com/matm/gocov-html/commit/0b8d15295cd34ca0b76338a94bd78383de8bda79#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) changed (besides the related code changes).

So, from now on you need to use
`go install github.com/matm/gocov-html/cmd/gocov-html@latest` (see the additional `/cmd/gocov-html`)

**Comment by msdean** [comment]
Ah, good ol' RTFM....
Thanks for the quick response :)

**Comment by vintagego** [comment]
Hi, is this resolved I have updated this dependency to go get github.com/matm/gocov-html/cmd/gocov-html however, its still breaking for me.

**Comment by msdean** [comment]
Tru `go install github.com/matm/gocov-html/cmd/gocov-html` instead of `go get github.com/matm/gocov-html/cmd/gocov-html` (`install` instead of `get`)
