### ISSUE TITLE
Last release breaks `go install`

### ISSUE THREAD

**Issue by jmdacruz** [matm/gocov-html#21]
Running `go install github.com/matm/gocov-html@latest` fails with the following error:
```
go install github.com/matm/gocov-html@latest: module github.com/matm/gocov-html@latest found (v1.1.1), but does not contain package github.com/matm/gocov-html
```

Installing with `go install github.com/matm/gocov-html@71874e2e203b87a703f46020febb9650f0f8320d` works fine

**Comment by jmdacruz** [comment]
I just realized this works: `go install github.com/matm/gocov-html/cmd/gocov-html@v1.1.1`

**Comment by lsr1991** [comment]
I also found the `go get` does not work:
`go get -u gopkg.in/matm/v1/gocov-html
package gopkg.in/matm/v1/gocov-html: no Go files in XXX/.gvm/pkgsets/go1.9.5/global/src/gopkg.in/matm/v1/gocov-html
go get github.com/matm/gocov-html    
package github.com/matm/gocov-html: no Go files in XXX/.gvm/pkgsets/go1.9.5/global/src/github.com/matm/gocov-html
`
Thanks @jmdacruz , I change the command to be 
`go get -u gopkg.in/matm/v1/gocov-html/cmd/gocov-html`
and it works.

**Comment by matm** [comment]
The `README.md` for 1.1.1 has been updated and the instruction do work:
```
$ go install github.com/matm/gocov-html/cmd/gocov-html@latest
```

@jmdacruz Note that your initial command is missing the `/cmd/` part in your path. See also #20.

**Comment by vintagego** [comment]
Hi, is this resolved I have updated this dependency to go get github.com/matm/gocov-html/cmd/gocov-html however, its still breaking for me.

**Comment by matm** [comment]
@vintagego Please read the README, the instructions have been updated and it reads:
```
$ go install github.com/matm/gocov-html/cmd/gocov-html@latest
```
