### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by lsr1991** [matm/gocov-html#26]
```
➜  go git:(master) ✗ go get -u gopkg.in/matm/v1/gocov-html/cmd/gocov-html
# github.com/matm/gocov-html/pkg/cov
XXX/.gvm/pkgsets/go1.11/global/src/github.com/matm/gocov-html/pkg/cov/report.go:161:17: undefined: io.ReadAll
```

**Comment by matm** [comment]
Are you using Go 1.11?

**Comment by anandpathak-gp** [comment]
yes. same issue is there for Go version < 1.16.

**Comment by matm** [comment]
Okay. That's because `io.ReadAll()` has been moved from `io/ioutil` since Go 1.16.

I didn't expect some of you guys are using old version of  the Go compiler. Anyway, I'm opening an issue to fix this.

**Comment by matm** [comment]
See #29

**Comment by obalunenko** [comment]
@matm @anandpathak-gp 
Even GO team supports only 3 latest versions
https://go.dev/doc/devel/release#policy

I'm not sure if it is correct to add support for such an old version.
The current release is 1.19 - so it's ok to support only 1.17 and 1.18, IMHO.

**Comment by matm** [comment]
I do agree @obalunenko, thanks for your feedback.

However, it didn't involve a lot of work to re-enable support for older versions some I'm fine with it -- for now. This may change in the future. My main concern for now is adding more features to this tool without disturbing current users.
