### ISSUE TITLE
Broken semver tag v1.2

### ISSUE THREAD

**Issue by obalunenko** [matm/gocov-html#35]
Hi @matm 
Tag [v1.2](https://github.com/matm/gocov-html/releases/tag/v1.2) is broken - it should be `v1.2.0`

GO supports only semver tags or commit hashes for public modules.
https://go.dev/blog/publishing-go-modules

When I'm trying to install the latest version go fetches only `v1.1.1`

```
go install github.com/matm/gocov-html/cmd/gocov-html@latest

go: downloading github.com/matm/gocov-html v1.1.1
go: downloading github.com/axw/gocov v1.1.0
```

When I try to install `v1.2` go throws an error

```
go install github.com/matm/gocov-html/cmd/gocov-html@v1.2

go: github.com/matm/gocov-html/cmd/gocov-html@v1.2: no matching versions for query "v1.2"
```

**Comment by matm** [comment]
Hi @obalunenko, thanks for reporting.

This is fixed. Tag `v1.2.0` now replaces `v1.2`.

**Comment by obalunenko** [comment]
Thanks @matm 
I tested it - it works like a charm now

**Comment by matm** [comment]
Nice to hear. Thanks for using it btw.
