### ISSUE TITLE
refac: generate Go code to render themes

### ISSUE THREAD

**Issue by matm** [matm/gocov-html#38]
Generating the code for methods `Beautifier.Template()` and `Beautifier.Data()` will ease theme management. This way `Beautifer.Assets()` can be used to simply define the required assets to build a theme.

- [x] Remove implementions of `Beautifier.Template()` and `Beautifier.Data()` for the `golang` (default) theme
- [x] Write a Go generator in `pkg/themes/generator.go` that will generate a `default_gen.go` file implementing those two methods with proper content taken from `Assets()`
- [x] Update the build system to `go generate` before building

**Comment by MdSahilGrab** [comment]
> Generating the code for methods `Beautifier.Template()` and `Beautifier.Data()` will ease theme management. This way `Beautifer.Assets()` can be used to simply define the required assets to build a theme.
> 
> * [x]  Remove implementions of `Beautifier.Template()` and `Beautifier.Data()` for the `golang` (default) theme
> * [x]  Write a Go generator in `pkg/themes/generator.go` that will generate a `default_gen.go` file implementing those two methods with proper content taken from `Assets()`
> * [x]  Update the build system to `go generate` before building

Hi @matm I don't see generator.go file in pkg/themes/ and we are getting this error
/../github.com/matm/gocov-html/pkg/themes/theme.go:9:14: cannot use defaultTheme{} (type defaultTheme) as type types.Beautifier in slice literal:
	defaultTheme does not implement types.Beautifier (missing Data method)

**Comment by matm** [comment]
Hi @MdSahilGrab , the generator code has been moved to `cmd/generator` on `master`. How do you get this error? How do you build it?

**Comment by MdSahilGrab** [comment]
Actually we have this command in Dockerfile **RUN go get github.com/matm/gocov-html/cmd/gocov-html**  which we are running when building the code.

**Comment by MdSahilGrab** [comment]
@matm  so you want to us to use  RUN go get github.com/matm/gocov-html/cmd/generator

**Comment by matm** [comment]
Okay, can you try with the latest stable release instead? Something like
```shell
RUN go install github.com/matm/gocov-html/cmd/gocov-html@latest
```

**Comment by MdSahilGrab** [comment]
Yes we tried but this is also not working

**Comment by matm** [comment]
> @matm so you want to us to use RUN go get github.com/matm/gocov-html/cmd/generator

Maybe this can help: https://github.com/matm/gocov-html/blob/master/build.mk#L73

**Comment by matm** [comment]
> Yes we tried but this is also not working

What if you do
```shell
RUN go install github.com/matm/gocov-html/cmd/gocov-html@v1.2.0
```

**Comment by MdSahilGrab** [comment]
Let me check

**Comment by MdSahilGrab** [comment]
Maybe this can help: https://github.com/matm/gocov-html/blob/master/build.mk#L73,
How exactly can i use this in dokerfile

**Comment by matm** [comment]
Can you paste a working sample of your `Dockerfile` here? I need more context, thank you.

**Comment by MdSahilGrab** [comment]
@matm yeah this is the Dockerfile we have now which was running successfully till yesterday
RUN ./coverage.sh
RUN go get github.com/jstemmer/go-junit-report
RUN go get github.com/axw/gocov/gocov
RUN go get github.com/AlekSi/gocov-xml
RUN go get github.com/matm/gocov-html/cmd/gocov-html
RUN go test -v -coverprofile=coverage.txt -covermode count ./... 2>&1 | go-junit-report > report.xml
RUN mkdir $GOPATH/coverage
RUN mkdir $GOPATH/lint
RUN gocov convert coverage.txt > coverage.json
RUN gocov-xml < coverage.json > $GOPATH/coverage/coverage.xml
RUN gocov-html < coverage.json > $GOPATH/coverage/index.html
RUN cp report.xml $GOPATH/coverage/report.xml
RUN cp lint_report.xml $GOPATH/lint/lint_report.xml

**Comment by matm** [comment]
This works:
```Dockerfile
FROM golang:1.16-alpine3.14
RUN go get github.com/axw/gocov/gocov
RUN go get github.com/matm/gocov-html/cmd/gocov-html
```
Then
```shell
$ docker build -t tool .
$ docker run --rm -ti tool gocov-html -h
Usage of gocov-html:
  -d    output CSS of default theme
  -lt
        list available themes
  -s string
        path to custom CSS file
  -t string
        theme to use for rendering (default "golang")
  -v    show program version
```

**Comment by MdSahilGrab** [comment]
@matm This we have in dockerfile but still its failing from yesterday  
`FROM golang:1.16-alpine3.14
RUN go get github.com/axw/gocov/gocov
RUN go get github.com/matm/gocov-html/cmd/gocov-html`

This

**Comment by MdSahilGrab** [comment]
Not sure its failing, will check internally

**Comment by obalunenko** [comment]
@matm What is the reason not to store generated code in git?

**Comment by matm** [comment]
@obalunenko Actually, I was thinking about it today. Also this would prevent increasing the major version number and keeping the `go install` working.

**Comment by matm** [comment]
v1.3.1 just released and fixes this annoying issue. `go install` works as usual now.
Thanks for your feedback guys.
